### ISSUE TITLE
Add Rotation as basic built-in component type with interpolation by default

### ISSUE THREAD

**Issue by tadej** [coherence/protocol-code-generator#127]
**Estimate:** 3 days

**Comment by eriksvedang** [comment]
I remember that @piot had some important ideas for how this data type should be designed and optimized (we discussed it when I was working on the puck showcase).

**Comment by piot** [comment]
Please elaborate @eriksvedang 

I have strong ideas that the types in the schema file should be *very* descriptive (describe threir intent), not how they are stored in memory. Direction vs Orientation. They can both be stored as a quaternion, but mean different things.
We should support common game types. Instead of using Int for everything, you describe them as Health, Armor, Score, Velocity, etc. That helps us representing them in a nicer way in our UIs as well.

Or did you mean more how to serialize them? 2D rotations can be store as an 8-bit value for example.

**Comment by eriksvedang** [comment]
Yeah I think it was both the design/vision of them, and how to serialize. My comment was more a reminder to the team to get your thoughts on it, if there's time to do so.
